### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by SecUpwN** [brarcher/gift-card-guard#12]
Good morning @brarcher, first of all: Thanks for developing this great app and especially for putting it on F-Droid! I am a very visual person and would like to see these small improvements to your `README`:
- Rename `gift-card-guard` to `Gift Card Guard` so that it corresponds to the published app name.
- Link an F-Droid button just like I added via pull request on another project called [Binaural Beats](https://github.com/GiorgioRegni/Binaural-Beats).
- Seems like you copied the `README` of your other project, otherwise this sentence would be erased:

> If there is any interest in improving this open source **baby monitor**, kindly submit a pull request with proposed changed.

**Comment by brarcher** [comment]
Thanks for your interest in the project. 

Thanks for the tips, all good points! I'll make the updates/corrections to the README.
