### ISSUE TITLE
Material design icon

### ISSUE THREAD

**Issue by betsythefc** [brarcher/gift-card-guard#28]
I'd like to design an icon that follows material design guidelines.

**Comment by brarcher** [comment]
That would be great! As you can see I'm not much of a graphic artist and the icon currently being used was thrown together. Your contribution would be much appreciated.

Do you know what license the icon will be covered under? The current icon is covered under the [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) license. I guess the question is does the project own the icon (in which case the license would be GPLv3) or do you retain ownership (in which case CC BY 3.0 would be acceptable)?

Would you also be interested in making an icon for the [Budget Watch](https://github.com/brarcher/budget-watch) application as well? It is the application I use most often and find the most useful. One may have more freedom in what the icon would be, as the application is not as literally named. Though, if you are not interested, that is perfectly OK. (:

**Comment by betsythefc** [comment]
I'd be happy to try making the icons! The project can own the icon, it doesn't matter to me but I have heard that the GPLv3 is not a good license for graphics so it could be licensed under the CC BY 3.0 but still owned by the project.

This would apply for all 3 icons I make assuming you like them :)

**Comment by betsythefc** [comment]
@brarcher Sorry I haven't created the icon for this project yet, but I really love the one you made!

**Comment by brarcher** [comment]
Oh, thanks! I wanted to put the app on the play store, and needed an icon which looked better at 512x512. If you think it is sufficient, then I can go with this one. Otherwise, feel free to propose another one. (:

**Comment by DavidXochipilli** [comment]
What do you think of this one, @betsythefc & @brarcher?

![48px](https://user-images.githubusercontent.com/29784866/33189822-d05b5a32-d0a6-11e7-9c3f-51f2ee340241.png)

[gift-card-guard_icon.zip](https://github.com/brarcher/gift-card-guard/files/1500268/gift-card-guard_icon.zip)

**Comment by brarcher** [comment]
I like it! Would you be interested in also creating a feature graphic for the Play store? Currently it looks like the following:

<img width="403" alt="screen shot 2017-11-23 at 9 02 51 pm" src="https://user-images.githubusercontent.com/5264535/33192612-ca5e1828-d091-11e7-84d0-62648ba0255e.png">

based on the existing app icon:

![ic_launcher](https://user-images.githubusercontent.com/5264535/33192638-f3ade000-d091-11e7-9c63-26a3b058de72.png)

It would need to be 1024 w x 500 h and a JPG or 24-bit PNG (no alpha).

**Comment by betsythefc** [comment]
I love that icon, it's better than anything I could have done. Kudos!

**Comment by DavidXochipilli** [comment]
Thanks @betsythefc 😘
I will do a feature graphic next week @brarcher 👌

**Comment by DavidXochipilli** [comment]
What do you think of it @brarcher & @betsythefc?
![googlefeaturegraphic](https://user-images.githubusercontent.com/29784866/33518273-7644efd4-d792-11e7-9f97-826bef8b91f6.png)

**Comment by betsythefc** [comment]
That is simple and gorgeous, you got my vote.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by brarcher** [comment]
It looks great! (:

I have a few questions.

1) What license do you provide these graphics under? If it was code it would be GPLv3 (same as the project), but I am less clear on image resources. I suspect a [Creative Commons](https://creativecommons.org/choose/) license would be appropriate, but it would be up to you if you want that and which variant. The most permissive would be [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

2) If you pick a CC license, I'll need to add an attribution to you in the app (the About dialog, accessible in the main activity's menu options). What name would you like me to use, and is there a URL you would like me to reference?

**Comment by DavidXochipilli** [comment]
I attached a .zip with everything inside. The content is under the CC0 1.0 Universal license.
Please use the name [Samy](https://plus.google.com/+SamyMarBoyTonny91) and link to [https://plus.google.com/+SamyMarBoyTonny91](https://plus.google.com/+SamyMarBoyTonny91). His GitHub handle is @samymarboy by the way.

[gift-card-guard.zip](https://github.com/brarcher/gift-card-guard/files/1525198/gift-card-guard.zip)
