### ISSUE TITLE
Mismatching version name

### ISSUE THREAD

**Issue by ghost** [brarcher/gift-card-guard#4]
You tagged version 0.1, but `app/build.gradle` says its 1.0. Could you release a version 0.2 with a matching tag? Also don't forget to increase the versioncode (from 1 to 2 or above).

**Comment by brarcher** [comment]
Oh, sorry about that.

A version 0.1.1 has now been released which besides adding unit tests only changes the versionName and versionCode.

Thanks for letting me know!
