### ISSUE TITLE
WebView disappears after device rotation

### ISSUE THREAD

**Issue by calbee633810** [brarcher/gift-card-guard#42]
Open About in Menu, WebView dialog shows. But it disppears after device rotation.

![screen shot 2018-04-13 at 3 53 03 pm](https://user-images.githubusercontent.com/38213896/38723152-ca2b21ec-3f32-11e8-8f24-29692b7e285e.png)
Screenshot before rotation

![screen shot 2018-04-13 at 3 53 10 pm](https://user-images.githubusercontent.com/38213896/38723161-cf3556bc-3f32-11e8-9f39-493c19331007.png)
Screenshot after rotation

**Comment by brarcher** [comment]
This should now be resolved, and will be fixed in the next release. Thanks for pointing it out.
