### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [brarcher/gift-card-guard#51]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 4 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on gift-card-guard (or its library dependencies). We documented these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve gift-card-guard's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by brarcher** [comment]
You are welcome to send me the gists.

**Comment by misterAnderson90** [comment]
Dear Branden Archer,

The CogniCrypt reported 4 issues related to the incorrect usage of the MessageDigest on third-party libraries. 

[Gist 01 - MessageDigest](https://gist.github.com/misterAnderson90/426b4af631b0912d0cb35de5ca6f5327)
[Gist 02 - MessageDigest](https://gist.github.com/misterAnderson90/0715cabb1262edaebc14f80114080334)
[Gist 03 - MessageDigest](https://gist.github.com/misterAnderson90/a92f4ca93aea7f1093d765693f4ca4dc)
[Gist 04 - MessageDigest](https://gist.github.com/misterAnderson90/8cb12b3ea8ba7079084bd7ddd30eb68f)

For any doubts, you can comment directly in the gists and we can clarify the issues.  

Best regards,

**Comment by brarcher** [comment]
These 4 findings all come from Google's Guava library. It may be better to raise an issue there instead:

https://github.com/danielnorberg/guava-libraries

**Comment by misterAnderson90** [comment]
Thanks, Branden

I'll raise an issue on Google's Guava library to get their perceptions about these warnings.
