### ISSUE TITLE
Change currency

### ISSUE THREAD

**Issue by airon90** [brarcher/gift-card-guard#8]
Is it possible to set currency by hand? By now I saw that it is a hardcoded string.
I'm Italian and I use euros, not US dollars ;)

**Comment by brarcher** [comment]
I'll add a setting for the currency symbol.

**Comment by brarcher** [comment]
A setting has been added which will configure the currency which is displayed. Can you take a look and see if this help out?

**Comment by brarcher** [comment]
If the issue is not resolved, let me know.

**Comment by airon90** [comment]
Is the update already live? I reinstalled the app from F-Droid (ver 0.1.1) and the dollar sign is already present.

**Comment by brarcher** [comment]
The $ may be the default, but it can be overridden in the settings menu to anything you like.

**Comment by airon90** [comment]
There is no way to change the currency. There is no gear icon, if I keep on pressing on the entry doesn't happen anything and if I edit the entry there is no option to change the currency.

**Comment by brarcher** [comment]
You are right. I mistakenly thought that the changes which add a setting for the currency was already release. However, it was not.

I have just cut a release, [v0.2](https://github.com/brarcher/gift-card-guard/releases/tag/v0.2), which will contain this change. When F-Droid picks it up in a day or so the main activity will contain a gear that will lead to the settings.

Thanks for pointing this out, sorry for the confusion.

**Comment by brarcher** [comment]
I'll reopen the issue, you can close it if the v0.2 release resolves your concern.

**Comment by airon90** [comment]
:+1:

**Comment by airon90** [comment]
This bug has been fixed in v. 0.2
Great! Thank you!
